/**
 * 腳本：為所有作者建立英文 slug
 * 使用方式：npx tsx scripts/update-author-slugs.ts
 */

import { createClient } from '@libsql/client'
import { drizzle } from 'drizzle-orm/libsql'
import { eq } from 'drizzle-orm'
import * as dotenv from 'dotenv'

// 載入 .env
dotenv.config()

// 中文到拼音對照表（常見字）
const pinyinMap: Record<string, string> = {
  '股': 'gu',
  '市': 'shi',
  '隱': 'yin',
  '者': 'zhe',
  '財': 'cai',
  '經': 'jing',
  '投': 'tou',
  '資': 'zi',
  '理': 'li',
  '金': 'jin',
  '融': 'rong',
  '錢': 'qian',
  '富': 'fu',
  '貴': 'gui',
  '大': 'da',
  '小': 'xiao',
  '王': 'wang',
  '李': 'li',
  '張': 'zhang',
  '陳': 'chen',
  '林': 'lin',
  '黃': 'huang',
  '劉': 'liu',
  '楊': 'yang',
  '吳': 'wu',
  '趙': 'zhao',
  '周': 'zhou',
  '徐': 'xu',
  '孫': 'sun',
  '馬': 'ma',
  '朱': 'zhu',
  '胡': 'hu',
  '郭': 'guo',
  '何': 'he',
  '高': 'gao',
  '羅': 'luo',
  '鄭': 'zheng',
  '梁': 'liang',
  '謝': 'xie',
  '宋': 'song',
  '唐': 'tang',
  '許': 'xu',
  '韓': 'han',
  '馮': 'feng',
  '鄧': 'deng',
  '曹': 'cao',
  '彭': 'peng',
  '曾': 'zeng',
  '蕭': 'xiao',
  '田': 'tian',
  '董': 'dong',
  '潘': 'pan',
  '袁': 'yuan',
  '蔡': 'cai',
  '蔣': 'jiang',
  '余': 'yu',
  '杜': 'du',
  '葉': 'ye',
  '程': 'cheng',
  '魏': 'wei',
  '蘇': 'su',
  '呂': 'lv',
  '丁': 'ding',
  '任': 'ren',
  '沈': 'shen',
  '姚': 'yao',
  '盧': 'lu',
  '姜': 'jiang',
  '崔': 'cui',
  '鍾': 'zhong',
  '譚': 'tan',
  '陸': 'lu',
  '汪': 'wang',
  '范': 'fan',
  '廖': 'liao',
  '石': 'shi',
  '熊': 'xiong',
  '賀': 'he',
  '方': 'fang',
  '雷': 'lei',
  '薛': 'xue',
  '侯': 'hou',
  '龍': 'long',
  '文': 'wen',
  '白': 'bai',
  '毛': 'mao',
  '江': 'jiang',
  '段': 'duan',
  '錢': 'qian',
  '湯': 'tang',
  '尹': 'yin',
  '黎': 'li',
  '易': 'yi',
  '常': 'chang',
  '武': 'wu',
  '喬': 'qiao',
  '賴': 'lai',
  '龔': 'gong',
  '洪': 'hong',
  '一': 'yi',
  '二': 'er',
  '三': 'san',
  '四': 'si',
  '五': 'wu',
  '六': 'liu',
  '七': 'qi',
  '八': 'ba',
  '九': 'jiu',
  '十': 'shi',
  '百': 'bai',
  '千': 'qian',
  '萬': 'wan',
  '億': 'yi',
  '先': 'xian',
  '生': 'sheng',
  '老': 'lao',
  '師': 'shi',
  '哥': 'ge',
  '姐': 'jie',
  '叔': 'shu',
  '伯': 'bo',
  '爺': 'ye',
  '奶': 'nai',
  '爸': 'ba',
  '媽': 'ma',
  '兄': 'xiong',
  '弟': 'di',
  '姊': 'zi',
  '妹': 'mei',
  '子': 'zi',
  '女': 'nv',
  '男': 'nan',
  '人': 'ren',
  '民': 'min',
  '國': 'guo',
  '家': 'jia',
  '地': 'di',
  '天': 'tian',
  '日': 'ri',
  '月': 'yue',
  '年': 'nian',
  '時': 'shi',
  '分': 'fen',
  '秒': 'miao',
  '東': 'dong',
  '西': 'xi',
  '南': 'nan',
  '北': 'bei',
  '中': 'zhong',
  '上': 'shang',
  '下': 'xia',
  '左': 'zuo',
  '右': 'you',
  '前': 'qian',
  '後': 'hou',
  '內': 'nei',
  '外': 'wai',
  '美': 'mei',
  '好': 'hao',
  '新': 'xin',
  '舊': 'jiu',
  '快': 'kuai',
  '慢': 'man',
  '長': 'chang',
  '短': 'duan',
  '多': 'duo',
  '少': 'shao',
  '全': 'quan',
  '半': 'ban',
  '真': 'zhen',
  '假': 'jia',
  '是': 'shi',
  '非': 'fei',
  '有': 'you',
  '無': 'wu',
  '能': 'neng',
  '會': 'hui',
  '可': 'ke',
  '以': 'yi',
  '要': 'yao',
  '不': 'bu',
  '很': 'hen',
  '太': 'tai',
  '更': 'geng',
  '最': 'zui',
  '都': 'dou',
  '也': 'ye',
  '還': 'hai',
  '再': 'zai',
  '又': 'you',
  '就': 'jiu',
  '才': 'cai',
  '只': 'zhi',
  '把': 'ba',
  '被': 'bei',
  '讓': 'rang',
  '給': 'gei',
  '對': 'dui',
  '和': 'he',
  '與': 'yu',
  '或': 'huo',
  '但': 'dan',
  '而': 'er',
  '如': 'ru',
  '果': 'guo',
  '因': 'yin',
  '為': 'wei',
  '所': 'suo',
  '這': 'zhe',
  '那': 'na',
  '哪': 'na',
  '誰': 'shui',
  '什': 'shen',
  '麼': 'me',
  '怎': 'zen',
  '樣': 'yang',
  '些': 'xie',
  '個': 'ge',
  '們': 'men',
  '的': 'de',
  '了': 'le',
  '著': 'zhe',
  '過': 'guo',
  '在': 'zai',
  '到': 'dao',
  '從': 'cong',
  '向': 'xiang',
  '往': 'wang',
  '於': 'yu',
  '用': 'yong',
  '以': 'yi',
  '為': 'wei',
  '作': 'zuo',
  '做': 'zuo',
  '說': 'shuo',
  '話': 'hua',
  '看': 'kan',
  '聽': 'ting',
  '想': 'xiang',
  '知': 'zhi',
  '道': 'dao',
  '見': 'jian',
  '來': 'lai',
  '去': 'qu',
  '走': 'zou',
  '跑': 'pao',
  '吃': 'chi',
  '喝': 'he',
  '玩': 'wan',
  '學': 'xue',
  '習': 'xi',
  '寫': 'xie',
  '讀': 'du',
  '問': 'wen',
  '答': 'da',
  '教': 'jiao',
  '愛': 'ai',
  '喜': 'xi',
  '歡': 'huan',
  '樂': 'le',
  '怕': 'pa',
  '怒': 'nu',
  '哭': 'ku',
  '笑': 'xiao',
  '開': 'kai',
  '關': 'guan',
  '門': 'men',
  '窗': 'chuang',
  '房': 'fang',
  '屋': 'wu',
  '樓': 'lou',
  '路': 'lu',
  '街': 'jie',
  '城': 'cheng',
  '村': 'cun',
  '山': 'shan',
  '水': 'shui',
  '河': 'he',
  '海': 'hai',
  '湖': 'hu',
  '島': 'dao',
  '花': 'hua',
  '草': 'cao',
  '樹': 'shu',
  '木': 'mu',
  '森': 'sen',
  '林': 'lin',
  '風': 'feng',
  '雨': 'yu',
  '雪': 'xue',
  '雲': 'yun',
  '霧': 'wu',
  '電': 'dian',
  '火': 'huo',
  '光': 'guang',
  '熱': 're',
  '冷': 'leng',
  '暖': 'nuan',
  '涼': 'liang',
  '春': 'chun',
  '夏': 'xia',
  '秋': 'qiu',
  '冬': 'dong',
  '早': 'zao',
  '晚': 'wan',
  '午': 'wu',
  '夜': 'ye',
  '明': 'ming',
  '暗': 'an',
  '黑': 'hei',
  '紅': 'hong',
  '橙': 'cheng',
  '黃': 'huang',
  '綠': 'lv',
  '藍': 'lan',
  '紫': 'zi',
  '青': 'qing',
  '灰': 'hui',
  '粉': 'fen',
  '色': 'se',
  '手': 'shou',
  '腳': 'jiao',
  '頭': 'tou',
  '臉': 'lian',
  '眼': 'yan',
  '耳': 'er',
  '鼻': 'bi',
  '嘴': 'zui',
  '牙': 'ya',
  '舌': 'she',
  '心': 'xin',
  '身': 'shen',
  '體': 'ti',
  '車': 'che',
  '船': 'chuan',
  '飛': 'fei',
  '機': 'ji',
  '書': 'shu',
  '筆': 'bi',
  '紙': 'zhi',
  '桌': 'zhuo',
  '椅': 'yi',
  '床': 'chuang',
  '衣': 'yi',
  '服': 'fu',
  '鞋': 'xie',
  '帽': 'mao',
  '食': 'shi',
  '物': 'wu',
  '菜': 'cai',
  '肉': 'rou',
  '魚': 'yu',
  '米': 'mi',
  '麵': 'mian',
  '酒': 'jiu',
  '茶': 'cha',
  '糖': 'tang',
  '鹽': 'yan',
  '油': 'you',
  '狗': 'gou',
  '貓': 'mao',
  '鳥': 'niao',
  '雞': 'ji',
  '鴨': 'ya',
  '豬': 'zhu',
  '牛': 'niu',
  '羊': 'yang',
  '馬': 'ma',
  '虎': 'hu',
  '龍': 'long',
  '蛇': 'she',
  '兔': 'tu',
  '鼠': 'shu',
  '公': 'gong',
  '司': 'si',
  '業': 'ye',
  '務': 'wu',
  '員': 'yuan',
  '主': 'zhu',
  '管': 'guan',
  '組': 'zu',
  '長': 'zhang',
  '部': 'bu',
  '廠': 'chang',
  '店': 'dian',
  '場': 'chang',
  '院': 'yuan',
  '校': 'xiao',
  '醫': 'yi',
  '藥': 'yao',
  '病': 'bing',
  '痛': 'tong',
  '死': 'si',
  '活': 'huo',
  '安': 'an',
  '危': 'wei',
  '險': 'xian',
  '難': 'nan',
  '易': 'yi',
  '問': 'wen',
  '題': 'ti',
  '事': 'shi',
  '情': 'qing',
  '感': 'gan',
  '覺': 'jue',
  '思': 'si',
  '想': 'xiang',
  '法': 'fa',
  '則': 'ze',
  '例': 'li',
  '式': 'shi',
  '型': 'xing',
  '類': 'lei',
  '種': 'zhong',
  '數': 'shu',
  '量': 'liang',
  '度': 'du',
  '點': 'dian',
  '面': 'mian',
  '線': 'xian',
  '角': 'jiao',
  '圓': 'yuan',
  '方': 'fang',
  '形': 'xing',
  '正': 'zheng',
  '反': 'fan',
  '同': 'tong',
  '異': 'yi',
  '等': 'deng',
  '級': 'ji',
  '低': 'di',
  '高': 'gao',
  '深': 'shen',
  '淺': 'qian',
  '厚': 'hou',
  '薄': 'bao',
  '重': 'zhong',
  '輕': 'qing',
  '強': 'qiang',
  '弱': 'ruo',
  '硬': 'ying',
  '軟': 'ruan',
  '乾': 'gan',
  '濕': 'shi',
  '淨': 'jing',
  '髒': 'zang',
  '香': 'xiang',
  '臭': 'chou',
  '甜': 'tian',
  '苦': 'ku',
  '酸': 'suan',
  '辣': 'la',
  '鹹': 'xian',
  '淡': 'dan',
  '價': 'jia',
  '格': 'ge',
  '錢': 'qian',
  '銀': 'yin',
  '行': 'hang',
  '戶': 'hu',
  '口': 'kou',
  '帳': 'zhang',
  '單': 'dan',
  '票': 'piao',
  '證': 'zheng',
  '券': 'quan',
  '基': 'ji',
  '期': 'qi',
  '貨': 'huo',
  '率': 'lv',
  '比': 'bi',
  '差': 'cha',
  '損': 'sun',
  '益': 'yi',
  '利': 'li',
  '潤': 'run',
  '賺': 'zhuan',
  '賠': 'pei',
  '買': 'mai',
  '賣': 'mai',
  '交': 'jiao',
  '易': 'yi',
  '訂': 'ding',
  '購': 'gou',
  '銷': 'xiao',
  '售': 'shou',
  '品': 'pin',
  '牌': 'pai',
  '標': 'biao',
  '誌': 'zhi',
  '記': 'ji',
  '號': 'hao',
  '名': 'ming',
  '稱': 'cheng',
  '字': 'zi',
  '詞': 'ci',
  '語': 'yu',
  '句': 'ju',
  '章': 'zhang',
  '節': 'jie',
  '段': 'duan',
  '篇': 'pian',
  '集': 'ji',
  '冊': 'ce',
  '卷': 'juan',
  '本': 'ben',
  '版': 'ban',
  '社': 'she',
  '報': 'bao',
  '紙': 'zhi',
  '網': 'wang',
  '站': 'zhan',
  '頁': 'ye',
  '台': 'tai',
  '視': 'shi',
  '影': 'ying',
  '片': 'pian',
  '劇': 'ju',
  '目': 'mu',
  '播': 'bo',
  '放': 'fang',
  '錄': 'lu',
  '音': 'yin',
  '頻': 'pin',
  '道': 'dao',
  '阿': 'a',
  '啊': 'a',
  '吧': 'ba',
  '呢': 'ne',
  '嗎': 'ma',
  '哦': 'o',
  '嗯': 'en',
  '哈': 'ha',
  '嘿': 'hei',
  '喂': 'wei',
  '哇': 'wa',
  '呀': 'ya',
  '耶': 'ye',
  '嘛': 'ma',
  '呵': 'he',
  '嘻': 'xi',
  '嘟': 'du',
  '咕': 'gu',
  '咚': 'dong',
  '咔': 'ka',
  '呱': 'gua',
  '叮': 'ding',
  '噹': 'dang',
  '嗒': 'da',
  '嘀': 'di',
  '咕': 'gu',
  '嚕': 'lu',
  '呼': 'hu',
  '哼': 'heng',
  '噢': 'o',
  '喔': 'o',
  '哎': 'ai',
  '唉': 'ai',
  '噓': 'xu',
  '噗': 'pu',
  '嘶': 'si',
  '嘎': 'ga',
  '嗡': 'weng',
  '嘣': 'beng',
  '咻': 'xiu',
  '轟': 'hong',
  '砰': 'peng',
  '啪': 'pa',
  '咣': 'guang',
  '叭': 'ba',
  '咩': 'mie',
  '喵': 'miao',
  '汪': 'wang',
  '嗚': 'wu',
  '霸': 'ba',
  '寶': 'bao',
  '柏': 'bai',
  '彪': 'biao',
  '鑫': 'xin',
  '達': 'da',
  '康': 'kang',
  '宇': 'yu',
  '軒': 'xuan',
  '澤': 'ze',
  '浩': 'hao',
  '博': 'bo',
  '睿': 'rui',
  '智': 'zhi',
  '傑': 'jie',
  '俊': 'jun',
  '豪': 'hao',
  '偉': 'wei',
  '華': 'hua',
  '建': 'jian',
  '國': 'guo',
  '志': 'zhi',
  '強': 'qiang',
  '剛': 'gang',
  '平': 'ping',
  '慶': 'qing',
  '亮': 'liang',
  '輝': 'hui',
  '勇': 'yong',
  '軍': 'jun',
  '峰': 'feng',
  '海': 'hai',
  '超': 'chao',
  '飛': 'fei',
  '鵬': 'peng',
  '雲': 'yun',
  '龍': 'long',
  '虎': 'hu',
  '麒': 'qi',
  '麟': 'lin',
  '鳳': 'feng',
  '祥': 'xiang',
  '瑞': 'rui',
  '福': 'fu',
  '祿': 'lu',
  '壽': 'shou',
  '喜': 'xi',
  '財': 'cai',
  '寧': 'ning',
  '靜': 'jing',
  '雅': 'ya',
  '秀': 'xiu',
  '麗': 'li',
  '娟': 'juan',
  '芳': 'fang',
  '蘭': 'lan',
  '梅': 'mei',
  '菊': 'ju',
  '蓮': 'lian',
  '英': 'ying',
  '玲': 'ling',
  '珍': 'zhen',
  '萍': 'ping',
  '霞': 'xia',
  '玉': 'yu',
  '雲': 'yun',
  '燕': 'yan',
  '紅': 'hong',
  '婷': 'ting',
  '穎': 'ying',
  '敏': 'min',
  '琳': 'lin',
  '瑩': 'ying',
  '倩': 'qian',
  '婉': 'wan',
  '琪': 'qi',
  '薇': 'wei',
  '嫻': 'xian',
  '蕊': 'rui',
}

// 將中文名字轉成拼音 slug
function toPinyinSlug(name: string): string {
  let result = ''

  for (const char of name) {
    if (pinyinMap[char]) {
      result += pinyinMap[char]
    } else if (/[a-zA-Z0-9]/.test(char)) {
      result += char.toLowerCase()
    } else if (/[\s\-_]/.test(char)) {
      result += '-'
    }
    // 忽略其他字符
  }

  // 清理連續的連字號和首尾連字號
  return result.replace(/-+/g, '-').replace(/^-|-$/g, '')
}

// 定義 authors 表結構（簡化版，不用 import schema）
const authorsTable = {
  name: 'authors',
}

async function main() {
  const url = process.env.TURSO_DATABASE_URL
  const authToken = process.env.TURSO_AUTH_TOKEN

  if (!url) {
    console.error('缺少 TURSO_DATABASE_URL 環境變數')
    process.exit(1)
  }

  console.log('連接資料庫...')
  const client = createClient({ url, authToken })

  // 記錄已使用的 slug
  const usedSlugs = new Set<string>()

  try {
    // 查詢所有作者
    console.log('查詢所有作者...')
    const result = await client.execute('SELECT id, name, slug FROM authors')

    console.log(`找到 ${result.rows.length} 位作者`)
    console.log('')

    // 先收集已有的 slug
    for (const row of result.rows) {
      const existingSlug = row.slug as string | null
      if (existingSlug) {
        usedSlugs.add(existingSlug)
      }
    }

    for (const row of result.rows) {
      const id = row.id as string
      const name = row.name as string
      const existingSlug = row.slug as string | null

      if (existingSlug) {
        console.log(`✓ ${name} 已有 slug: ${existingSlug}`)
        continue
      }

      let baseSlug = toPinyinSlug(name)

      if (!baseSlug) {
        // 如果無法生成 slug，用 id 的前 8 位作為後備
        baseSlug = `author-${id.slice(0, 8)}`
        console.log(`⚠ ${name} 使用後備 slug: ${baseSlug}`)
      }

      // 確保 slug 唯一
      let newSlug = baseSlug
      let counter = 2
      while (usedSlugs.has(newSlug)) {
        newSlug = `${baseSlug}-${counter}`
        counter++
      }

      usedSlugs.add(newSlug)

      console.log(`→ ${name} -> ${newSlug}`)

      // 更新資料庫
      try {
        await client.execute({
          sql: 'UPDATE authors SET slug = ?, updated_at = ? WHERE id = ?',
          args: [newSlug, Math.floor(Date.now() / 1000), id],
        })
        console.log(`  ✓ 已更新`)
      } catch (error: any) {
        console.log(`  ✗ 更新失敗: ${error.message}`)
      }
    }

    console.log('')
    console.log('完成！')
  } catch (error) {
    console.error('錯誤:', error)
    process.exit(1)
  } finally {
    client.close()
  }
}

main()
